name: GCC BUILD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
       sudo apt update && sudo apt install -y libcairo2-dev libfontconfig-dev libfreetype-dev libfreetype6 libfreetype6-dev libxcb1-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-ewmh-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libharfbuzz-dev libfontconfig1-dev libasound2-dev pkg-config
    - name: configure
      run: ./configure
    - name: build source
      run: make
